name: Generate Cypress Report

on:

push:

branches:

-'main'

jobs:

cypress-test:

name: Run on Chrome 99

runs-on: ubuntu-18.04

I container: cypress/browsers: node12.18.0-chrome83-ff77 steps:

uses: actions/checkout@v2

- name: Install cypress and verify run: |

npm ci

$(npm bin)/cypress verify

name: Run Cypress tests
run: npm run test: chrome continue-on-error: false

- name: Copy test execution videos and screenshots run: |

mkdir public

cp -r cypress/videos public/videos

cp -r cypress/screenshots public/screenshots
- name: Merge test reports

run: npm run combine:report

name: Generate HTML report run: npm run generate:report
 env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY}}
